<?php

$settings['config_sync_directory'] = dirname(DRUPAL_ROOT) . '/config';

$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';

// #ddev-generated: Automatically generated Drupal settings file.
if (file_exists($app_root . '/' . $site_path . '/settings.ddev.php') && getenv('IS_DDEV_PROJECT') == 'true') {
  include $app_root . '/' . $site_path . '/settings.ddev.php';
}

$settings['reverse_proxy'] = TRUE;
$settings['reverse_proxy_addresses'] = array($_SERVER['REMOTE_ADDR']);

// <DDSETTINGS>
// Please don't edit anything between <DDSETTINGS> tags.
// This section is autogenerated by Acquia Dev Desktop.
if (isset($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR']) && file_exists($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/loc_decoupled_solr_dd.inc')) {
  require $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/loc_decoupled_solr_dd.inc';
}
// </DDSETTINGS>
$databases['default']['default'] = array (
  'database' => 'decoupled_solr',
  'username' => 'drupaluser',
  'password' => '',
  'prefix' => '',
  'host' => '127.0.0.1',
  'port' => 33067,
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
$settings['hash_salt'] = '-mJgn6LRWVtZimam_egKOBZwh3iMtn8qzh43LxNm2AwdWYLlMNPLNyRUsUROEmbt0BgMJdYx1Q';
